{% set version = "0.12.0" %}

package:
  name: rtoml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/rtoml/rtoml-{{ version }}.tar.gz
  sha256: 662e56bd5953ee7ebcc5798507ae90daa329940a5d5157a48f3d477ebf99c55b

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
  host:
    - maturin >=1,<2
    - pip
    - python
  run:
    - python

test:
  requires:
    - coverage
    - dirty-equals
    - pip
    - pytest
    - pytest-speed
  source_files:
    - example.py
    - tests
  imports:
    - rtoml
  commands:
    - pip check
    - coverage run --source rtoml --branch -m pytest -vv --tb=long -k "not datetime_invalid"
    - coverage report --show-missing --skip-covered --fail-under=100

about:
  home: https://github.com/samuelcolvin/rtoml
  license: MIT
  license_file: LICENSE
  summary: A fast TOML library for python implemented in rust.

extra:
  recipe-maintainers:
    - thewchan
